# SWE546_Assignment4

MovieLens Recommendation System

http://grouplens.org/datasets/movielens/

Using the MovieLens 1M dataset, and using only the rankings, implement a recommendation sytem using SGD.

import pandas as pd

rnames = ['user_id', 'movie_id', 'rating', 'timestamp'] ratings = pd.read_table('data/ml-1m/ratings.dat', sep='::', header=None, names=rnames)

The output of your program must be the highest estimated rankings for the first 10 movies of the first 20 users

In [1]:
import pandas as pd
import numpy as np

rnames = ['user_id', 'movie_id', 'rating', 'timestamp'] 
ratings = pd.read_table('ml-1m/ratings.dat', sep='::', header=None, names=rnames)

/Users/onurtokoglu/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators; you can avoid this warning by specifying engine='python'.


In [2]:
Ys = np.mat(ratings)[:,0:3]
numUser = np.max(Ys[:,0])
numMov = np.max(Ys[:,1])
print("userId - movieId - rating")
print(Ys[0:3,:])

userId - movieId - rating
[[   1 1193    5]
 [   1  661    3]
 [   1  914    3]]


In [16]:
k = 20

A = np.mat(np.random.rand(numUser,k))
B = np.mat(np.random.rand(k,numMov))

iterationCount = 10
Eta = 0.1


In [17]:
def CalculateError(Ys,A,B):
    error = 0.0
    for i in range(len(Ys)):
        ui = Ys[i,0] - 1
        mi = Ys[i,1] - 1
        err = A[ui,:]*B[:,mi] - Ys[i,2]
        error += (err*err)[0,0]
    return error/len(Ys)

In [18]:
import sys

for i in range(iterationCount):
    
    print(CalculateError(Ys,A,B))
    sys.stdout.flush()
        
    for j in range(len(Ys)):
        uj = Ys[j,0] - 1
        mj = Ys[j,1] - 1
        err = Ys[j,2] - A[uj,:]*B[:,mj]
        tempA = A[uj,:] + Eta*(1/(i+1)) * err[0,0] * B[:,mj].T
        B[:,mj] = B[:,mj] + Eta*(1/(i+1)) * err[0,0] * A[uj,:].T
        A[uj,:] = tempA
        

4.23901069465
1.4285585952
0.838054266818
0.710782737198
0.653196474055
0.620264906882
0.598722462204
0.583473324674
0.572090225435
0.563249159233


In [19]:
print("Predictions\n")

pred = A[0:20,:]*B[:,0:10]

print(pred)

print("---------")

for i in range(20):
    maxIndex = np.argmax(pred[i,:])
    print("User "+str(i+1)+" --> Movie "+str(maxIndex+1))

Predictions

[[ 4.65007553  3.68359664  3.09795736  3.7163917   3.87640863  3.82727189
   3.77848976  4.02902148  3.0359538   3.63646448]
 [ 3.96051607  3.17867021  3.41020582  3.74625753  3.55250962  3.77567929
   3.74588319  3.36820779  2.48824681  3.48416801]
 [ 3.60159761  3.31371988  3.91843859  3.09020875  3.29529884  4.17656884
   4.40253602  3.95343078  2.95756683  3.53973295]
 [ 4.3454929   3.01565265  3.32399121  3.58342624  3.12100202  4.45201224
   3.77583532  3.00094603  2.35857899  3.6347705 ]
 [ 3.387439    1.74479207  1.40429676  2.40439532  0.81702741  2.95579922
   1.71817125  2.45393098  1.18877833  2.21655483]
 [ 4.0767361   3.79098764  4.66546177  3.63367714  4.71542636  3.53625128
   4.80230421  4.34905737  2.71967516  3.8491981 ]
 [ 4.39239048  3.67315512  3.95461939  3.49604492  3.12937079  4.50370819
   3.80676354  4.21465111  3.19284122  4.44510867]
 [ 4.86606782  3.79462615  2.68661442  2.63199357  3.11452836  4.29374191
   3.21081695  2.47858642  2.95761975 